name = "ipfs"

[defaults]
builder = "docker:node"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[builders."docker:node"]
enabled = true
skip_runtime_image = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "http"
instances = { min = 1, max = 200, default = 1 }

[[testcases]]
name = "bitswap"
instances = { min = 1, max = 200, default = 1 }

  [testcases.params]
  multiaddr = { type = "string", default = "never" }
  cidsfile = { type = "string", default = "cids" }
  wanttype = { type = "string", default = "have" }

